name = "leap"
version = "0.1.0"
defaultTargets = ["Python", "Raylib", "maze", "snake", "fs"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "RealAnalysis"

[[lean_lib]]
name = "Python"

[[lean_lib]]
name = "Raylib"

[[lean_exe]]
name = "maze"
root = "Maze"

[[lean_exe]]
name = "snake"
root = "Snake"

[[lean_exe]]
name = "slider"
root = "Slider"

[[lean_exe]]
name = "tasks"
root = "Tasks"

[[lean_exe]]
name = "tt"
root = "TasksTest"

[[lean_exe]]
name = "fs"
root = "FileSize"

[[lean_exe]]
name = "main"
root = "Main"

[[lean_exe]]
name = "mol"
root = "MarkdownOfLean"

[[lean_exe]]
name = "brainfuck"
root = "BrainFuck"

[[lean_exe]]
name = "led"
root = "Tasks.LED"